### ISSUE TITLE
LoadBalance_results

### ISSUE THREAD

**Issue by manjusang7** [park-project/park#11]
Here is a discussion with @hongzimao.

I have some questions regarding the Figure 4 (k) Load balancing in Park paper.

![Park_load](https://user-images.githubusercontent.com/38546555/80112462-218caf00-854f-11ea-8ef7-95f037dcd9c4.jpg)

1.      What does the x-axis “Number of actions” mean? I tried to understand the terminologies in the figure by making comparison with 2.3 The 10-armed testbed in “RL: An Introduction second edition, Richard Sutton and Andrew G. Barto.”  Is the “Number of actions” the same as runs?

2.      Is the “Testing total reward” of y-axis an average total reward of multiple trainings of runs?

Thanks for your interest! For your questions:

1. The number of actions literally means number of actions take by all agents so far during training (notice that there can be multiple distributed worker thread collecting experience). In other words, this number is the same as number of MDP steps experienced by all workers combined. It’s different from “runs” (I’m assuming “runs" means “episodes”) — one episode contains multiple MDP steps hence multiple actions.

Also, the environment is quite different from the example in chapter 2.3 of Sutton’s book. The dynamics of the environment is described in appendix A, server load balancing.

2. It should be the total reward of an episode averaged over many testing episodes.

**Comment by manjusang7** [comment]
Thank you @hongzimao for the explanation.

I let one episode include 1e8 actions by changing '--num_stream_jobs', type=int, default=1e8 in param.py. But I got a figure like this. It seems in the beginning reward is 0, it decreases as number of actions (number of jobs) increases.

![Figure_1 (1)](https://user-images.githubusercontent.com/38546555/80113686-a1ffdf80-8550-11ea-8392-e3bf77d07cbe.jpg)

**Comment by hongzimao** [comment]
It looks like the reward decreases to ~2*10-8. But jobs shouldn't last this long. If the load of the system is below 100%, the whole system is draining jobs all the time, so jobs should get processed (all policies are work-conservative). This figure means the policy is not strong enough to keep up with the workload. You might want to decrease the system load by increasing the server processing rate, or by increasing the job inter-arrival time. 

One thing worth noting is that this environment doesn't reset on its own (see paper section 3.2 Infinite horizon problems). A random initial policy might struggle to learn (can't keep up with the workload and see progressively worsen rewards). We got the learning curve with a curriculum learning (similar to the approach detailed in section 5.3 challenge #1 of this paper: https://people.csail.mit.edu/hongzi/content/publications/Decima-Sigcomm19.pdf, also an illustration in page 22-25 of slides https://people.csail.mit.edu/hongzi/content/publications/Decima-Sigcomm19.pptx). Operationally, what we did is basically resetting the environment when a counter on steps hits threshold T. And we increase T over time. 

Hope these help!

**Comment by hongzimao** [comment]
I'm confused - what data did you log to plot this figure? It looks like the reward decreases to ~2*10-8. A job shouldn't last this long: the whole system is draining jobs all the time, the load is <100% so jobs should get processed (all policies are work-conservative). 

One thing worth noting is that this environment doesn't reset on its own (see paper section 3.2 Infinite horizon problems). We got the learning curve with a curriculum learning (similar to the approach detailed in section 5.3 challenge 1 of this paper: https://people.csail.mit.edu/hongzi/content/publications/Decima-Sigcomm19.pdf, also an illustration in )
