### ISSUE TITLE
Congestion control -- missing config param

### ISSUE THREAD

**Issue by bbalaji-ucsd** [park-project/park#14]
I tried to run the congestion control environment, and got the following error. It looks like the configuration parameters of the environment is missing.

```
INFO:root:Mahimahi setup
100% [........................................................................] 42890119 / 42890119Traceback (most recent call last):
  File "random_agent.py", line 4, in <module>
    env = park.make('congestion_control')
  File "/home/ubuntu/Repositories/park/park/envs/registration.py", line 77, in make
    return registry.make(env_id)
  File "/home/ubuntu/Repositories/park/park/envs/registration.py", line 53, in make
    env = spec.make()
  File "/home/ubuntu/Repositories/park/park/envs/registration.py", line 36, in make
    env = cls()
  File "/home/ubuntu/Repositories/park/park/envs/congestion_control/congestion_control.py", line 127, in __init__
    self.setup_mahimahi()
  File "/home/ubuntu/Repositories/park/park/envs/congestion_control/congestion_control.py", line 239, in setup_mahimahi
    self.linkDelay = park.param.config.cc_delay
AttributeError: 'Namespace' object has no attribute 'cc_delay'
```

**Comment by hongzimao** [comment]
Hmm it seems these parameters for the congestion control environment is missing from the master branch: https://github.com/park-project/park/blob/42d5b19338e53c03a7708bf6593c2ee948e5fc39/park/param.py#L117-L120. 

Could you try adding them and see if it works? Would be nice if you submit a pull request for this fix afterwards too. Thanks!

cc @akshayknarayan

**Comment by akshayknarayan** [comment]
looks like they were accidentally removed here: https://github.com/park-project/park/commit/5effdc1a76feebc8128e3c154ffe394083a9539d#diff-ea4dae23bbf0786a89f141ef9f84ad99L124

**Comment by hongzimao** [comment]
Okay seems like a branch merge causes this accident. I've added the parameters back https://github.com/park-project/park/commit/f1eb4758fdbca08c3ba5524dbfd9b234281e4a54. @parimarjan please also make sure there isn't code alternation outside query optimization environments.

**Comment by bbalaji-ucsd** [comment]
Thank you! Can confirm that the fix worked.
