### ISSUE TITLE
Congestion control -- missing step() function

### ISSUE THREAD

**Issue by bbalaji-ucsd** [park-project/park#15]
Thanks for resolving the configuration issues in the congestion control environment.

I tried to run a random agent as given in the documentation, but found that the environment does not implement a step function.
```
import park

env = park.make('load_balance')

obs = env.reset()
done = False

while not done:
    # act = agent.get_action(obs)
    act = env.action_space.sample()
    obs, reward, done, info = env.step(act)
```

This is the error I got:
```
Traceback (most recent call last):
  File "random_agent.py", line 11, in <module>
    state, reward, done, info = env.step(action)
AttributeError: 'CongestionControlEnv' object has no attribute 'step'
FATAL: exception not rethrown
Aborted (core dumped)
```

How do I use this environment? Is there an agent I can use?

**Comment by hongzimao** [comment]
This congestion control environment interacts with the real underlying system. For this environment, the most straightforward logic is to provide an agent for the environment and let the environment run and consult the agent for action. This is different from the "agent-centric" logic where the agent explicitly "step" the environment forward. This is introduced in the park paper figure 3. So the interaction template you can try is (copied from repo README.md)
```
Real system interface
import park
import agent_impl  # implemented by user

env = park.make('congestion_control')

# the run script will start the real system
# and periodically invoke agent.get_action
agent = Agent(env.observation_space, env.action_space)
env.run(agent)
The agent_impl.py should implement

class Agent(object):
    def __init__(self, state_space, action_space, *args, **kwargs):
        self.state_space = state_space
        self.action_space = action_space

    def get_action(self, obs, prev_reward, prev_done, prev_info):
        act = self.action_space.sample()
        # implement real action logic here
        return act
```

**Comment by hongzimao** [comment]
I'm assuming you are using the congestion control environment (since your last question is about CC and the error is `AttributeError: 'CongestionControlEnv' object has no attribute 'step'`). Though the code snippet you provided on the top was about `load_balance` environment.

**Comment by bbalaji-ucsd** [comment]
Thanks @hongzimao !

Yes, I'm using the congestion control environment. I just copy pasted the `load_balance` from the Readme. 

With the modified Agent class, I'm not able to use standard RL libraries. Can you provide the Agent implementations used in the paper?

**Comment by hongzimao** [comment]
You can try this implementation of A2C https://www.dropbox.com/sh/anycesu538ecd65/AAB1HTifIMmXCvZRnQxp9KOCa?dl=0

I believe you can modify most standard RL libraries for this "environment-centric" interaction. The main difference is where to log the experience (at env.step or at agent call) and where to trigger a training step (inside agent call with a counter, for example).

**Comment by bbalaji-ucsd** [comment]
Got it. Thanks!
