### ISSUE TITLE
About load_balance RL agent

### ISSUE THREAD

**Issue by lesleychou** [park-project/park#20]
Hi @hongzimao,

Thanks for your well-commented work!

I am trying to reproduce the Server load balancing results from Fig.4 in the paper. 
![image](https://user-images.githubusercontent.com/28391838/111855614-3c3af400-8969-11eb-9412-962f83945a76.png)

However, after I added the A2C agent, the reward is not increasing over 1e9 epochs. I debugged my A2C agent, it learned successfully in three OpenAI gym envs.

I am wondering if it is possible for you to share the agent file you had for load balancing? If so it would be greatly helpful for us!

**Comment by hongzimao** [comment]
This load balancer example should be similar to one of other paper: http://people.csail.mit.edu/hongzi/var-website/index.html (see section 6.2 and figure 5). The A2C agent is open sourced in https://github.com/hongzimao/input_driven_rl_example/blob/master/load_balance_actor_agent.py hope it's helpful for your scenario.

**Comment by lesleychou** [comment]
Thank you! It's extremely helpful, I was able to reproduce the paper results.
Sincerely appreciate your active response as always!
