### ISSUE TITLE
problem setting the Vagrant for the project

### ISSUE THREAD

**Issue by saeid93** [park-project/park#7]
Hi,
Sorry if this is not directly related to project, I am new with using Vagrant, I get the following error when I want to set up this repo:
![Screenshot from 2020-01-01 22-44-39](https://user-images.githubusercontent.com/6298780/71647026-5e0a7580-2ce8-11ea-9d31-7aea83593a69.png)
any solution?
thanks

**Comment by hongzimao** [comment]
I believe the Vagrant setting is for the congestion control environment. Can you try including park in python and initiate the environment with `env = park.make('congestion_control')`? The setup code should bootstrap the environment and its dependencies https://github.com/park-project/park/blob/master/park/envs/congestion_control/congestion_control.py#L111-L127 (cc'ing @akshayknarayan for more help)

**Comment by akshayknarayan** [comment]
Re: Vagrant error, you may have to update your virtualbox version - see here: https://stackoverflow.com/questions/39345370/vboxmanage-error-details-code-ns-error-failure-0x80004005-with-meanjs-and-v#39366133

@saeid93 I am closing this for now, but feel free to reopen if there's a problem.
